export const GET_USERS = 'GET_USERS'
export const SET_SEARCHED_USERS = 'SET_SEARCHED_USERS'
export const SET_SEARCHED_GROUP_USERS = 'SET_SEARCHED_GROUP_USERS'
export const DELETE_SEARCHED_USER = 'DELETE_SEARCHED_USER'
export const NULLIFY_SEARCHED_USERS = 'NULLIFY_SEARCHED_USERS'
export const ADD_NEW_USER = 'ADD_NEW_USER'
export const DELETE_SEARCHED_GROUP_USER = 'DELETE_SEARCHED_GROUP_USER'
export const NULLIFY_SEARCHED_GROUP_USERS = 'NULLIFY_SEARCHED_GROUP_USERS'

